project:
  type: website
  output-dir: docs

website:
  title: " MKTG100 Numeracy Skills [BETA VERSION]" 
  author: "Ahmad Daryanto (Anto)"
  date: "11/04/2022"
  body-header: | 
      Michaelmas Term 2023
  margin-header: | 
      ![](cover.png)
  theme:
      light: flatly
      dark: darkly
  page-navigation: true
  page-footer: " Creator Ahmad Daryanto, Last Update: Nov 2022"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Introduction"
        contents:
          - index.qmd
      - section: "Week 5"
        contents:
          - week5.qmd
      - section: "Week 6"
        contents:
          - week6.qmd
      - section: "Week 7"
        contents:
          - week7a.qmd
          - week7b.qmd
      - section: "Week 8"
        contents:
          - week8a.qmd   
          - week8b.qmd 
      - week9.qmd
      - section: "Solutions"
        contents:
          - sol5.qmd
          - sol6.qmd
          - sol7a.qmd
  

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true

editor: visual

