Solutions to weekly problems and exercises

# Week 5 {.unnumbered}

## 1.2 What Is Arithmetic {.unnumbered}

**Problem**

What is the answer to a multiplication problem called? `Product`

**Exercises**

1.  What is the answer to a multiplication problem called? `Product`

2.  What is the answer to a division problem called? `Quotient`

3.  What is the answer to an addition problem called? `Sum`

4.  What is the answer to a subtraction problem called? `Difference`

## 1.3 Order of Operations: BODMAS rule {.unnumbered}

**Problem**

How to work this out: 10:2(2+1) = 15

**Exercises**

1.  3 + 4 \* 2 = 11

2.  ( 1 + 2 ) 5 - 2 \* 3 = 9

3.  8 : 2 ( 2 + 1 ) = 12

4.  2 - 2 + 2 = 2

5.  (10 : 2) \* 3 - 2 = 13

6.  5 \* $5^2$ = 125

## 1.4 Prime Numbers {.unnumbered}

**Problem**

Is 5 a prime number? `Yes`

**Exercises**

1.  Is 13 a prime number? `Yes`

2.  Is 33 a prime number? `No`

## 1.5 Prime Factorization {.unnumbered}

**Problem**

Find the prime factorization of 75. `3*5*5` = 3\*$5^2$

**Exercises**

1.  Find the prime factorization of 136. `2*2*2*17`= $2^3*17$

2.  Find the prime factorization of 100. `2*2*5*5`= $2^2*5^2$

3.  Find the prime factorization of 124. `2*2*31`= $2^2 * 31$

## 1.6 Greatest Common Factor {.unnumbered}

**Problem**

What is the greatest common divisor of 18 and 21? `3`

**Exercises**

1.  Find the hcf of 12 and 20. `4`

2.  Find the gcd of 35 and 100. `5`

3.  Find the gcd of 3 and 12. `3`

## 1.7 Lowest Common Factors {.unnumbered}

**Problem**

Find the lcm of 6 and 10. `30`

**Exercises**

1.  Find the lcm of 2 and 5. `10`

2.  Find the lcm of 3 and 6. `6`
