---
title: "Solutions to weekly problems and exercises: Week 7a"
format:
  pdf:
    toc: true
    number-sections: true
    highlight-style: github
---


# Week 7a {.unnumbered}

### 1.2 Percentages and Ratio {.unnumbered}

**Problem**

Transform 3.6 into a percentage.

$\frac{36}{10}=\frac{360}{100}=360 \%$

**Exercises**

1.  Transform 2.5 into a percentage.

$\frac{25}{10}=\frac{250}{100}=250 \%$

2.  Calculate 12% of 60. `7.2`

3.  Calculate 11.4% of 100. `11.4`

## 1.3 Calculating Percentages Changes {.unnumbered}

**Problems**

-   Last month, 250 consumers bought a new smartphone. This month, the number is 420. What is the percentage increase in sale?

$\frac{420-250}{250} \times 100 \% =\frac{170}{250} \times 100 \% =68 \%$

-   This year, your monthly rent is £750. Next year,the monthly rent is reduced by 5%. Calculate the new rent.

The new rent is $(100 \% - 5 \%) \times £ 750 = 95 \% \times £750 = £712.5$

**Exercises**

1.  Last month, 250 consumers bought a new smartphone. This month, the number is down to 100. What is the percentage decrease in sale?

$\frac{100-250}{250} \times 100 \% =\frac{-150}{250} \times 100 \% = -0.6 \times 100 \% = -60 \%$. In an absolute term, the percentage reduction is 60%.

2.  Yesterday there were 250 unique visitors clicking a website. Today, you found that there is a 10% increase in visit. How many clicks are there today?

$110 \% \times 250 = 275$
