# Week 7a: Percentages and Ratio

## Learning goals

-   Understand the meaning of percentages and ratio.
-   Know how to perform calculation with percentages and ratio.
-   Know how to calculate percentage changes.

## Percentages and Ratio

### Problem

Transform 3.6 into a percentage.

### Watch

<iframe width="560" height="315" src="https://www.youtube.com/embed/JeVSmq1Nrpw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

[Click this video](https://www.youtube.com/embed/JeVSmq1Nrpw)

### Exercises

1.  Transform 2.5 into a percentage.

2.  Calculate 12% of 60.

3.  Calculate 11.4% of 100.

## Calculating Percentages Changes

$$
Percentages \; changes = \frac{Change \; between \; values}{Original \;value} \times 100 \%   \label{eq1}
$$ $$
  = \frac{New \; value - Original \;value}{Original \;value} \times 100 \%  \label{eq2}
$$

-   If the percentage change is positive, it is called a percentage increase.

-   If the percentage change is negative, it is called a percentage decrease.

**Calculating new price**.

This year, your monthly rent is £750. Next year, the monthly rent is increased by 4%. Calculate the new rent.

Answer: The new rent is $(100 \% + 4 \%) \times £ 750 = 104 \% \times £750 = £780$

### Problem

-   Last month, 250 consumers bought a new smartphone. This month, the number is 420. What is the percentage increase in sale?

-   This year, your monthly rent is £750. Next year, the monthly rent is reduced by 5%. Calculate the new rent.

### Watch

<iframe width="560" height="315" src="https://www.youtube.com/embed/QZs8y0Y_3Vk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

[Click this video](https://www.youtube.com/embed/QZs8y0Y_3Vk)

### Exercises

1.  Last month, 250 consumers bought a new smartphone. This month, the number is down to 100. What is the percentage decrease in sale?

2.  Yesterday there were 250 unique visitors clicking a website. Today, you found that there is a 10% increase in visit. How many clicks are there today?

## Attempt the Exercises on Moodle

At this point, you would have worked on the above exercise questions.

Now, I want you to attempt these questions on Moodle.

Please click the link below:

[Week 7a Exercises on Moodle](https://modules.lancaster.ac.uk/mod/quiz/view.php?id=2468615)

Once you submit all your answers on Moodle, you complete your learning on this week's topic.
