# Week 7b: Exponents and Roots

## Learning Goals

-   Know how to evaluate exponential expressions
-   Know how to write exponential expressions when multiplying or dividing with the same base.
-   Know how to find roots.

## Exponents

Rules:

1.  $a^m \times a^n = a^{m+n}$

2.  $\frac{a^m}{a^n} = a^{m-n}$

3.  $(a^m)^n=a^{mn}$

4.  $a^{-m}=\frac{1}{a^{m}}$

### Problems

Simply:

1.  $x^2 \times x^3$ = ...

2.  $\frac{3^5}{3^2}$ = ...

3.  $(4^5)^2$ = ...

4.  $2^{-3}$ = ...

### Watch

<iframe width="560" height="315" src="https://www.youtube.com/embed/-zUmvpkhvW8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

[Click this video](https://www.youtube.com/embed/-zUmvpkhvW8)

### Exercises

Simply:

1.  $z^3 \times z^2$ = ...

2.  $\frac{4^3}{4^2}$ = ...

3.  $(5^2)^3$ = ...

4.  $3^{-2}$ = ...

## Attempt the Exercises on Moodle

At this point, you would have worked on the above exercise questions.

Now, I want you to attempt these questions on Moodle.

Please click the link below:

[Week 7a Exercises on Moodle](https://modules.lancaster.ac.uk/mod/quiz/view.php?id=2012499)

Once you submit all your answers on Moodle, you complete your learning on this week's topic.

## Roots

**Square roots**. 4 is called a square root of 16 because $4^2=16$. The symbol $\sqrt[2]{}$ or $\sqrt{}$ is used to represent square root. For example, $\sqrt{16}=4$. $\sqrt{16}$ can be written as $16^\frac{1}{2}$.

**Cube roots**. 2 is called a cube root of 8 because $2^3=8$. The symbol $\sqrt[3]{}$ is used to represent cube root. For example, $\sqrt[3]{8}=2$. $\sqrt[3]{8}$ can be written as $8^\frac{1}{3}$.

\*\* In general, $\sqrt[n]{a}$ can be written as $a^\frac{1}{n}$. It is hard sometimes to evaluate this expression manually. You can use a scientific calculator or `Excel` to do it. For example, by typing `=16^(1/4)` in `Excel`, it gives 2. That is $\sqrt[4]{16}=16^\frac{1}{4}=2$. You can prove that $2 \times 2 \times 2 \times 2 = 16$

### Problems

Evaluate $\sqrt[3]{16}$ (you can use a scientific calculator or `Excel`)

### Watch

<iframe width="560" height="315" src="https://www.youtube.com/embed/B4zejSI8zho" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

[Click this video](https://www.youtube.com/embed/B4zejSI8zho)

### Exercises

Evaluate

1.  $\sqrt[3]{81}$

2.  $\sqrt[4]{256}$

3.  $\sqrt{81}$

4.  $\sqrt[3]{216}$

5.  $\sqrt[4]{625}$

6.  $\sqrt[3]{15.63}$

## Attempt the Exercises on Moodle

At this point, you would have worked on the above exercise questions.

Now, I want you to attempt these questions on Moodle.

Please click the link below:

[Week 7b Exercises on Moodle](https://modules.lancaster.ac.uk/course/section.php?id=582964)

Once you submit all your answers on Moodle, you complete your learning on this week's topic.
