# Week 8b: Market Share

## Learning Goals

-   Understand market share

## Market Share

Market share of a firm is the firm's market share of the served market. Market share is one of the determinants how profitable a business is. A firm that has a high market share is more likely to be profitable than their smaller-share competitors. Market share can be calculated based on sales: the percentage of firm's sales obtained by the firm:

Market Share (%) = (Firm's Sales / Total Market Sales) × 100

### Problem

Firm A and Firm B are two companies competing in the luxury car market. Firm A sold 330k units last year, while Firm B sold 440k units in the same period. Calculate the market share of each company based on the given sales figures.

### Watch

<iframe width="560" height="315" src="https://www.youtube.com/embed/7XifAlvu7-k" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

[Click this video](https://www.youtube.com/embed/7XifAlvu7-k)

### Exercises

1.  In the leather jacket market, two companies are the main players in the market that fiercely compete to each other. Company X reported GBP 120 million in sales last year, while Company Y reported GBP 80 million. Calculate the market share based on the sales revenue.

Now, imagine that Company X launches a new marketing campaign that increases its sales to \$140 million this year, while Company Y's sales remain the same. Calculate the new market shares for both companies.

2.  Read this statement: "In June 2023, Facebook's market share reached 55 percent in the United Kingdom..." ([www.statista.com](https://www.statista.com/statistics/280301/market-share-held-by-facebook-in-the-united-kingdom-uk/))

Which of the following is the correct interpretation of the above statement?

A\) The percentage of UK's population using Facebook in June 2023.

B\) The percentage of Facebook's global users located in the United Kingdom.

C\) The percentage of total advertising revenue generated by Facebook in the UK.

D\) The percentage of UK's internet users using Facebook compared to other platforms.

## Attempt the Exercises on Moodle

At this point, you would have worked on the above exercise questions.

Now, I want you to attempt these questions on Moodle.

Please click the link below:

[Week 8b Exercises on Moodle](https://modules.lancaster.ac.uk/mod/quiz/view.php?id=2235177)

Once you submit all your answers on Moodle, you have completed your learning on this week's topic.
