# Week 5: Arithmetic

## Learning Goals

-   Understand what arithmetic is
-   Understand BODMAS rule
-   Understand Prime numbers
-   Know to how do prime factorisation
-   Understand highest common factors (hcf) / greatest common divisor (gcd)
-   Understand lowest common factors (lcm)

## What Is Arithmetic?

Arithmetic is a branch of mathematics that deals with numbers and their operations, which includes addition, subtraction, multiplication, and division.

### Problem

What is the answer to a multiplication problem called?

Select the correct answer:

a\. Product

b\. Sum

c\. Quotient

d\. Difference

### Watch

<iframe width="560" height="315" src="https://www.youtube.com/embed/IwW0GJWKH98" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

### Exercises

1.  What is the answer to a multiplication problem called?

2.  What is the answer to a division problem called?

3.  What is the answer to an addition problem called?

4.  What is the answer to a subtraction problem called?

## Order of Operations: BODMAS rule

"Operations" refer to mathematical operations such as addition, subtraction, multiplication, division, taking power ($a^n$) or roots ($\sqrt[n]{a}$) (note: $\sqrt[n]{a}=a^{1/n}$).

### Problem

How to work this out: 10:2(2+1) = ?

What to do first? The answer is BODMAS.

BODMAS = **B**racket, **O**rder, **D**ivision, **M**ultiplication, **A**ddition, and **S**ubtraction.

| Symbol |    Meaning     | Operation | Priority |
|:------:|:--------------:|:---------:|:--------:|
|   B    |    Bracket     |   $()$    |    1     |
|   O    |     Order      |   $a^n$   |    1     |
|   D    |    Division    |  $\div$   |    2     |
|   M    | Multiplication | $\times$  |    2     |
|   A    |    Addition    |    $+$    |    3     |
|   S    |  Subtraction   |    $-$    |    3     |

: Order of Operations and Priority

::: callout-important
You work out an expression from left to right in the order of BODMAS. Division and Multiplication are interchangeable (i.e., they have the same priority) and depend on which comes first in the expression. Similar rule applies for addition and subtraction as they have the same priority.
:::

### Watch

<iframe width="560" height="315" src="https://www.youtube.com/embed/ClYdw4d4OmA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

::: callout-note
## Millions people got it wrong: 6:2(1+2) = ?

A BODMAS problem 6:2(1+2) got viral on the internet. Read the news here

<https://www.newsweek.com/this-viral-math-problem-has-internet-frenzy-1584710>

Watch the explanation in the video below.

<iframe width="560" height="315" src="https://www.youtube.com/embed/URcUvFIUIhQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>
:::

### Exercises

Note: \* symbol is the same as $\times$

1.  3 + 4 \* 2 = ...

2.  ( 1 + 2 ) 5 - 2 \* 3 = ...

3.  8 : 2 ( 2 + 1 ) = ...

4.  2 - 2 + 2 = ...

5.  (10 : 2) \* 3 - 2 = ...

6.  5 \* $5^2$ = ...

## Prime Numbers

### Problem

Is 5 a prime number?

### Watch

<iframe width="560" height="315" src="https://www.youtube.com/embed/mIStB5X4U8M" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

### Exercises

1.  Is 13 a prime number?

2.  Is 33 a prime number?

## Prime Factorization

### Problem

Find the prime factorization of 75.

### Watch

<iframe width="560" height="315" src="https://www.youtube.com/embed/ZKKDTfHcsG0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

### Exercises

1.  Find the prime factorization of 136.

2.  Find the prime factorization of 100.

3.  Find the prime factorization of 124.

## Greatest common factors (gcd)

The greatest common divisor (gcd) is also called the highest common factor (hcf). GCD of two numbers is the number that divides them both. For instance GCD of 3 and 6 is 3.

### Problem

What is the greatest common divisor of 18 and 21?

### Watch

<iframe width="560" height="315" src="https://www.youtube.com/embed/uE9O8N5JYB4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

### Exercises

1.  Find the hcf of 12 and 20.

2.  Find the gcd of 35 and 100.

3.  Find the gcd of 3 and 12.

### Check Your Calculation

::: callout-warning
## Excel

Type in:

= GCD(3,6,12)

press `Enter`
:::

## Lowest common factors (lcm)

The lowest common factors is also called the the lowest common multiple. LCM of number A (say 2) and B (say 5) is the lowest number that can be divided by A and B without a remainder. For example, the lcm for 2 and 5 is 10 because 10 can be divided by 2 and 5 without a remainder.

### Problem

Find the lcm of 6 and 10.

### Watch

<iframe width="560" height="315" src="https://www.youtube.com/embed/RMJs_I9Nydw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

</iframe>

### Exercises

1.  Find the lcm of 2 and 5.

2.  Find the lcm of 3 and 6.

### Check Your Calculation

::: callout-warning
## Excel

Type in

= LCM (3,6)

press `Enter`
:::

## Attempt the Exercises on Moodle

At this point, you would have worked on the above exercise questions.

Now, I want you to attempt these questions on Moodle.

Please click the link below:

[Week 5 Exercises on Moodle](https://modules.lancaster.ac.uk/mod/quiz/view.php?id=2012123)

Once you submit all your answers on Moodle, you have completed your learning on this week's topic.
